# Generated by Django 5.2.4 on 2025-07-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
