# Generated by Django 5.2.4 on 2025-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_registeruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
